
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academia?useTimezone=true&serverTimezone=UTC&useLegacyData
    username: main
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update